apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          ports:
            - containerPort: 8081
          image: ghcr.io/vikramfa1/developer-utility-app:latest
      imagePullSecrets:
        - name: github-registry-secret


